# yaml-language-server: $schema=https://json.schemastore.org/github-issue-forms.json
name: Bug
description: File a bug report.
labels: ["bug"]
assignees:
  - ditwanp
body:
  - type: markdown
    attributes:
      value: |
        Thanks for logging an issue, I appreciate the feedback! Please confirm the following before continuing:
        - You are using the latest version, since the issue may already be fixed.
        - There are no [existing issues](/../../issues?q=is%3Aopen+is%3Aissue+label%3Abug) with the same bug report.
            - If there is a duplicate issue, please add a 👍 reaction instead of creating a new one.
  - type: checkboxes
    id: existing-issues
    attributes:
      label: Check existing issues
      description: If someone has already opened an issue for what you are experiencing, please add a 👍 reaction to the existing issue instead of creating a new one. For support, please check the [community forum](https://developers.arcgis.com/calcite-design-system/community/).
      options:
        - label: I have [checked for existing issues](https://github.com/ditwanp/action-testing/issues) to avoid duplicates
          required: true
  - type: dropdown
    id: component
    validations:
      required: true
    attributes:
      label: Which Component
      description: Which component(s) are related to this issue? (Select all that apply).
      multiple: true
      options:
        - N/A
        - Accordion
        - Accordion Item
        - Action
        - Action Bar
        - Action Group
        - Action Pad
        - Alert
        - Autocomplete
        - Autocomplete Item
        - Autocomplete Item Group
        - Avatar
        - Block
        - Block Group
        - Block Section
        - Button
        - Card
        - Card Group
        - Carousel
        - Carousel Item
        - Checkbox
        - Chip
        - Chip Group
        - Color Picker
        - Combobox
        - Combobox Item
        - Combobox Item Group
        - Date Picker
        - Dialog
        - Dropdown
        - Dropdown Group
        - Dropdown Item
        - Fab
        - Filter
        - Flow
        - Flow Item
        - Icon
        - Inline Editable
        - Input
        - Input Date Picker
        - Input Message
        - Input Number
        - Input Text
        - Input Time Picker
        - Input Time Zone
        - Label
        - Link
        - List
        - List Item
        - List Item Group
        - Loader
        - Menu
        - Menu Item
        - Meter
        - Modal
        - Navigation
        - Navigation Logo
        - Navigation User
        - Notice
        - Option
        - Option Group
        - Pagination
        - Panel
        - Popover
        - Progress
        - Radio Button
        - Radio Button Group
        - Rating
        - Scrim
        - Segmented Control
        - Segmented Control Item
        - Select
        - Sheet
        - Shell
        - Shell Center Row
        - Shell Panel
        - Slider
        - Split Button
        - Stepper
        - Stepper Item
        - Swatch
        - Swatch Group
        - Switch
        - Tab
        - Tab Nav
        - Tab Title
        - Table
        - Table Cell
        - Table Header
        - Table Row
        - Tabs
        - Text Area
        - Tile
        - Tile Group
        - Tile Select
        - Tile Select Group
        - Time Picker
        - Tip
        - Tip Group
        - Tip Manager
        - Tooltip
        - Tree
        - Tree Item
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear description of the issue (optionally include before/after screenshots/GIFs).
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected instead, and why?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Reproduction Steps
      description: Clear, numbered steps for reproducing the issue.
      placeholder: |
        1. Do xyz...
        2. Check the logs for an error ...
        3. ...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Reproduction Version
      description: The latest version that reproduces the issue
      placeholder: v0.0.0 # x-release-please-version
    validations:
      required: true
  - type: input
    id: regression
    attributes:
      label: Regression?
      description: Please provide the last working version if the issue is a regression. If a valid version number is entered, the issue will be considered a regression and prioritized accordingly.
    validations:
      required: false
  - type: textarea
    id: relevant
    attributes:
      label: Relevant Info
      description: Environment, logs, related issues, suggestions/resources on how to fix, etc.
    validations:
      required: false
