name: Accessibility
description: Report an accessibility issue in a component
labels: ["a11y", "bug", "0 - new", "needs triage"]
body:
  - type: checkboxes
    id: existing-issues
    attributes:
      label: Check existing issues
      description: If someone has already opened an issue for what you are experiencing, please add a 👍 reaction to the existing issue instead of creating a new one. For support, please check the [community forum](https://developers.arcgis.com/calcite-design-system/community/).
      options:
        - label: I have [checked for existing issues](https://github.com/ditwanp/action-testing/issues) to avoid duplicates and reviewed the [Accessibility page](https://developers.arcgis.com/calcite-design-system/foundations/accessibility) for guidance.
          required: true
  - type: dropdown
    id: which-component
    validations:
      required: false
    attributes:
      label: Which Component
      description: Which component(s) are related to this issue? (Select all that apply).
      multiple: true
      options:
        - N/A
        - A Test Component
        - A Test Component Three
        - A Test Component Two
        - Accordion
        - Accordion Item
        - Action
        - Action Bar
        - Action Group
        - Action Pad
        - Alert
        - Autocomplete
        - Autocomplete Item
        - Avatar
        - Block
        - Block Group
        - Block Section
        - Button
        - Card
        - Card Group
        - Carousel
        - Carousel Item
        - Checkbox
        - Chip
        - Chip Group
        - Color Picker
        - Combobox
        - Combobox Item
        - Combobox Item Group
        - Date Picker
        - Dialog
        - Dropdown
        - Dropdown Group
        - Dropdown Item
        - Fab
        - Filter
        - Flow
        - Flow Item
        - Icon
        - Inline Editable
        - Input
        - Input Date Picker
        - Input Message
        - Input Number
        - Input Text
        - Input Time Picker
        - Input Time Zone
        - Label
        - Link
        - List
        - List Item
        - List Item Group
        - Loader
        - Menu
        - Menu Item
        - Meter
        - Modal
        - Navigation
        - Navigation Logo
        - Navigation User
        - Notice
        - Option
        - Option Group
        - Pagination
        - Panel
        - Popover
        - Progress
        - Radio Button
        - Radio Button Group
        - Rating
        - Scrim
        - Segmented Control
        - Segmented Control Item
        - Select
        - Sheet
        - Shell
        - Shell Center Row
        - Shell Panel
        - Slider
        - Split Button
        - Stepper
        - Stepper Item
        - Swatch
        - Swatch Group
        - Switch
        - Tab
        - Tab Nav
        - Tab Title
        - Table
        - Table Cell
        - Table Header
        - Table Row
        - Tabs
        - Text Area
        - Tile
        - Tile Group
        - Tile Select
        - Tile Select Group
        - Time Picker
        - Tip
        - Tip Group
        - Tip Manager
        - Tooltip
        - Tree
        - Tree Item
  - type: textarea
    id: summary
    attributes:
      label: Summary
    validations:
      required: false
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear description of the issue (optionally include before/after screenshots/GIFs).
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected instead, and why?
    validations:
      required: true
  - type: input
    id: sample
    attributes:
      label: Reproduction Sample
      description: |
        We provide the following templates to help get started...
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Reproduction Steps
      description: Clear, numbered steps for reproducing the issue using the sample provided above.
      placeholder: |
        1. Open the DevTools console
        2. Click on XYZ
        3. ...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Reproduction Version
      description: The latest version that reproduces the issue.
    validations:
      required: true
  - type: input
    id: w3c
    attributes:
      label: Working W3C Example/Tutorial
      description: Link to valid w3c example for reference.
    validations:
      required: false
  - type: textarea
    id: relevant
    attributes:
      label: Relevant Info
      description: Browser, OS, tools, mobile, stack traces, related issues, suggestions/resources on how to fix, etc.
      placeholder: |
        Windows 10, Chrome 97, JAWS, NVDA, VoiceOver, Dragon
        `Uncaught TypeError: Cannot read property of undefined`
        ...
    validations:
      required: false
  - type: input
    id: regression
    attributes:
      label: Regression?
      description: Please provide the last working version if the issue is a regression.
    validations:
      required: false
  - type: dropdown
    id: priority-impact
    validations:
      required: true
    attributes:
      label: Priority impact
      multiple: false
      description: What is the impact to you, your team, or organization? Use discretion and only select "need" or "emergency" priorities for high user impact and quality issues. For instance, would someone notice, in a bad way, if this issue were present in the release?
      options:
        - impact - p3 - not time sensitive
        - impact - p2 - want for an upcoming milestone
        - impact - p1 - need for current milestone
        - impact - p0 - emergency
  - type: checkboxes
    id: packages
    attributes:
      label: Calcite package
      description: Select the relevant packages related to the request.
      options:
        - label: "@acme/acme-components"
        - label: "@acme/acme-components-react"
        - label: "@acme/acme-design-tokens"
        - label: "@acme/acme-plugin-calcite-components"
  - type: dropdown
    id: acme-team
    validations:
      required: true
    attributes:
      label: ACME team
      multiple: false
      description: If you work at ACME, please select your product team. Otherwise choose "N/A". If your team is not listed, choose "N/A", and then edit the line after submitting the issue.
      options:
        - N/A
        - ACME (design)
        - ACME (dev)
