name: Close Need More Info Issues

on:
  schedule:
    - cron: "*/5 * * * *" # Runs every 5 minutes for testing
    # - cron: "45 22 * * *" # Runs daily at 10:30 PM UTC (2:30 PM PST)
  workflow_dispatch: # Allows manual trigger

permissions:
  issues: write

jobs:
  close-needs-more-info-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Close issue if more info is not provided
        uses: actions/github-script@v7
        with:
          script: |
            const action = require('${{ github.workspace }}/.github/scripts/closeNeedsMoreInfoIssues.js')
            await action({github, context, core})
