name: Issue Notifications
on:
  issues:
    types: [labeled]
jobs:
  determine-action:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v4

      - name: "Archive ready for dev issues in design projects"
        if: github.event.label.name == 'ready for dev'
        uses: actions/github-script@v7
        env:
          GITHUB_TOKEN: ${{ secrets.PROJECTS_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          LABEL_NAME: ${{ github.event.label.name }}
        with:
          script: |
            const action = require('${{ github.workspace }}/.github/scripts/archiveIssuesInDesignProjects.js')
            await action({github, context, core})
