name: Remove PR from changelog
on:
  issues:
    types: [opened, labeled]
jobs:
  product-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add omit comment to PR
        uses: actions/github-script@v7
        with:
          script: |
            const action = require('${{ github.workspace }}/.github/scripts/omitPrFromChangelog.js')
            await action({github, context, core})
