name: Add Issue Labels
on:
  issues:
    types: [opened, labeled]
jobs:
  product-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add Esri Product Label
        uses: actions/github-script@v7
        with:
          script: |
            const action = require('${{ github.workspace }}/.github/scripts/omitPrFromChangelog.js')
            await action({github, context, core})
