name: Update Issue Template Components
on:
  push:
    paths:
      - "packages/src/components/**"
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm ci || true
      - name: Run updater
        run: |
          node .github/scripts/updateIssueTemplateComponents.js
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .github/ISSUE_TEMPLATE/1-bug.yml
          git commit -m "chore: update issue template component lists" || echo "No changes to commit"
          git push || echo "Push failed"
